Guide
-----

.. toctree::
   :maxdepth: 2

   installation
   getting_started
   tutorial/index
   cli/index


Tutorial
--------


Reference
---------

.. toctree::
    :maxdepth: 2

    api
    reference/all_classes
    reference/module_peachy
    reference/peachy.audio
    reference/peachy.config
    reference/peachy.etc
    reference/peachy.fs
    reference/peachy.geo
    reference/peachy.graphics
    reference/peachy.stage
    reference/peachy.ui
    reference/peachy.utils

More
----

.. toctree::
    :maxdepth: 2

    license
